[tool.poetry]
name = "securedrop-workstation-docs"
version = "0.0.1"
description = ""
authors = ["SecureDrop team <securedrop@freedom.press>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sphinx = "^6.1.3"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.2.0"
